### ISSUE TITLE
App does not record sound

### ISSUE THREAD

**Issue by ghost** [thanh-nguyen-kim/Android_Screen_Recorder_Plugin#1]
Hi,

Thanks a lot for the plugin it is really nice!
On my phone (Huawei API 23), the app does not record sound, do you know what could be the problem ?

**Comment by ghost** [comment]
I tried on a different phone and it works, the problem might be with Huawei and mp4.

**Comment by stickylabdev** [comment]
but damn ,mee too ,,, im in samsung it doesnot work ,,,,
